const TRANSLATION = {
	en: {
		global: {
			cookies: {
				title: "Cookies",
				description:
					"This website uses cookies to ensure you get the best experience. Information about language and theme preferences are stored in cookies.",
				buttons: {
					accept: "Accept cookies",
					acceptNecessary: "Accept necessary only",
					decline: "Decline all cookies",
				},
			},
			cookiesPreferences: {
				title: "Cookies preferences",
				description:
					"Accept necessary cookies to enable language and theme switching. To participate in analytics, accept all cookies.",
			},
			contact: {
				btnTxt: "Contact me",
				dialog: {
					title: "Contact me",
					subtitle: "Get in contact through your preferred social channel!",
					closeBtn: "Close",
				},
			},
			footer: {
				updated: "updated lastly",
				favicon: "favicon by Freepik",
			},
			navbar: {
				shortcuts: ["Home", "About", "Skills", "Projects", "Experience"],
			},
			projectPanel: {
				flagShip: "FLAGSHIP",
				newProject: "NEW",
			},
			theme: {
				light: "Light",
				dark: "Dark",
				system: "System",
			},
		},
		index: {
			aboutme: {
				title: "ABOUT ME",
				subtitle: "Enthusiastic problem-solver dedicated to web development",
			},
			experience: {
				title: "EXPERIENCE",
				header: "Quick summary of my most recent experiences",
				present: "Present",
			},
			newproject: {
				title: "CONTACT",
				hero: {
					title: "Get started!",
					subtitle: "Got a project in mind? Let's chat.",
				},
			},
			projects: {
				title: "PROJECTS",
				header: "Things I've built so far",
				moreBtn: {
					btnText: "and more...",
				},
			},
			skills: {
				title: "SKILLS",
				headers: {
					skills: "Technologies and tools I am good with",
					learning: "Additionally I'm currently learning",
				},
				listBtn: {
					showMore: "SHOW MORE",
					showLess: "SHOW LESS",
				},
				imgCredits: "Logos and images are generated by shields.io",
			},
			title: {
				header: {
					hello: "Hello, I'm",
					subtitle:
						"a passionate computer science student dedicated to mastering cutting-edge technologies and shaping the future as a skilled problem-solver and worker of the digital age.",
				},
				messageBtn: {
					btnTxt: "Send me a message",
					dialog: {
						title: "Send me a message",
						subtitle: "You reach me best via Telegram.",
						closeBtn: "Close",
					},
				},
				video: {
					overlays: {
						responsive: "RESPONSIVE",
						modern: "MODERN",
					},
					credits: "video by u_vt453kmgmm from Pixabay",
				},
			},
		},
		projects: {
			header: {
				title: "Projects",
				subtitle: "Curated catalogue of my recent work.",
			},
			footer: {
				title:
					"Find even more projects and the source code for this portfolio website on my GitHub!",
				btnText: "Check my GitHub",
			},
			newProject: {
				new: "NEW",
				dialog: {
					title: "New project in mind?",
					subtitle: "Get in contact and let's discuss how to proceed.",
					closeBtn: "Close",
				},
			},
		},
		project: {
			header: {
				backToProjectsBtn: {
					btnText: "Back to list",
				},
				sourceCodeBtn: {
					btnText: "View source code on GitHub",
					private: "Source code is private",
				},
			},
			demoLink: {
				btnText: "Check the live project on web",
				explotrack: "Check the demo project on web",
				deployedOn: "Deployed on",
			},
			video: {
				notWorking: {
					title: "Video not working?",
					btnText: "Open the video in Dropbox",
				},
				smallScreen: {
					title: "You are viewing this video on a really small screen!",
					subtitle:
						"If possible, I'd suggest switching to landscape mode for a better view.",
				},
			},
			description: {
				title: "Description",
			},
			learnMore: {
				private: {
					header: "Unfortunately the source code is private.",
					subtitle:
						"I'll still be happy to answer any questions you might have!",
					btnText: "Contact me fore more info",
				},
				public: {
					header: "Want to learn more about this project?",
					subtitle:
						"Check the source code and read the full documentation on GitHub!",
					btnText: "Check the GitHub repo",
				},
			},
			navbar: {
				title: "Check other projects as well!",
			},
		},
		notFound: {
			title: "404",
			subtitle:
				"This is not the page you are looking for. Please check the URL.",
			btnText: "Return home",
		},
	},
	fi: {
		global: {
			cookies: {
				title: "Evästeet",
				description:
					"Tämä verkkosivu hyödyntää evästeitä parhaan käyttökokemuksen varmistamiseksi. Tieto kielivalinnasta ja teemasta tallennetaan evästeisiin.",
				buttons: {
					accept: "Hyväksy evästeet",
					acceptNecessary: "Hyväksy vain välttämättömät",
					decline: "Kiellä kaikki evästeet",
				},
			},
			cookiesPreferences: {
				title: "Evästeasetukset",
				description:
					"Välttämättömät evästeet tarvitaan kielen ja teeman vaihtoon. Sivuston käytöstä kerätään analytiikkaa, mikäli hyväksyt kaikki evästeet.",
			},
			contact: {
				btnTxt: "Ota yhteyttä",
				dialog: {
					title: "Ota yhteyttä",
					subtitle: "Mikä kanava sopisi sinulle parhaiten?",
					closeBtn: "Sulje",
				},
			},
			footer: {
				updated: "päivitetty viimeksi",
				favicon: "faviconin suunnitellut Freepik",
			},
			navbar: {
				shortcuts: ["Koti", "Lyhyesti", "Taidot", "Projektit", "Työkokemus"],
			},
			projectPanel: {
				flagShip: "LIPPULAIVA",
				newProject: "UUSI",
			},
			theme: {
				light: "Vaalea",
				dark: "Tumma",
				system: "Järjestelmä",
			},
		},
		index: {
			aboutme: {
				title: "LYHYESTI",
				subtitle:
					"Motivoitunut web-kehitykseen erikoistunut ongelmanratkaisija",
			},
			experience: {
				title: "TYÖKOKEMUS",
				header: "Työkokemus",
				present: "Nykyhetki",
			},
			newproject: {
				title: "OTA YHTEYTTÄ",
				hero: {
					title: "Aloitetaan!",
					subtitle: "Projekti mielessä? Keskustellaan.",
				},
			},
			projects: {
				title: "PROJEKTIT",
				header: "Mitä olen tehnyt tähän mennessä",
				moreBtn: {
					btnText: "ja enemmän...",
				},
			},
			skills: {
				title: "TAIDOT",
				headers: {
					skills: "Teknologiat ja työkalut jotka hallitsen",
					learning: "Tällä hetkellä opettelen myös",
				},
				listBtn: {
					showMore: "NÄYTÄ ENEMMÄN",
					showLess: "NÄYTÄ VÄHEMMÄN",
				},
				imgCredits: "Logot ja kuvat generoi sivusto shields.io",
			},
			title: {
				header: {
					hello: "Hei, olen",
					subtitle:
						"omistautunut tietojenkäsittelytieteiden opiskelija, joka pyrkii hallitsemaan viimeisimpiä teknologioita ja muokkaamaan tulevaisuutta taitavana ongelmanratkaisijana ja digiajan työntekijänä.",
				},
				messageBtn: {
					btnTxt: "Lähetä minulle viesti",
					dialog: {
						title: "Lähetä minulle viesti",
						subtitle: "Parhaiten tavoitat Telegramin kautta.",
						closeBtn: "Sulje",
					},
				},
				video: {
					overlays: {
						responsive: "RESPONSIIVINEN",
						modern: "MODERNI",
					},
					credits: "video Pixabaysta käyttäjältä u_vt453kmgmm",
				},
			},
		},
		projects: {
			header: {
				title: "Projektit",
				subtitle: "Valikoitu lista uusimpia töitäni.",
			},
			footer: {
				title:
					"Löydä kaikki projektini ja lähdekoodi tälle portfolio-nettisivulle GitHubistani!",
				btnText: "Avaa GitHub-profiilini",
			},
			newProject: {
				new: "UUSI",
				dialog: {
					title: "Projekti mielessä?",
					subtitle: "Ota yhteyttä ja keskustellaan miten edettäisiin.",
					closeBtn: "Sulje",
				},
			},
		},
		project: {
			header: {
				backToProjectsBtn: {
					btnText: "Takaisin listaan",
				},
				sourceCodeBtn: {
					btnText: "Näytä lähdekoodi GitHubissa",
					private: "Lähdekoodi on yksityinen",
				},
			},
			demoLink: {
				btnText: "Tsekkaa live-projekti netissä",
				explotrack: "Tsekkaa demo-projekti netissä",
				deployedOn: "Projektin hostaa",
			},
			video: {
				notWorking: {
					title: "Eikö video toimi?",
					btnText: "Avaa video Dropboxissa",
				},
				smallScreen: {
					title: "Katsot videota todella pieneltä näytöltä!",
					subtitle:
						"Jos mahdollista, suosittelisin kääntämään laitteen vaaka-asentoon paremman katselukokemuksen saamiseksi.",
				},
			},
			description: {
				title: "Tarkempi kuvaus",
			},
			learnMore: {
				private: {
					header: "Valitettavasti projektin lähdekoodi on yksityinen.",
					subtitle: "Vastaan silti mielelläni kaikkiin kysymyksiin!",
					btnText: "Ota yhteyttä ja kysy lisää",
				},
				public: {
					header: "Haluaisitko tietää projektista vielä lisää?",
					subtitle:
						"Tutustu lähdekoodiin ja lue koko dokuementaatio GitHubissa!",
					btnText: "Avaa GitHub repo",
				},
			},
			navbar: {
				title: "Tutustu myös muihin projekteihin!",
			},
		},
		notFound: {
			title: "404",
			subtitle: "Tällaista sivua ei ole olemassakaan! Varmista oikea osoite.",
			btnText: "Takaisin etusivulle",
		},
	},
};

export default TRANSLATION;
